<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{f6213912-7d9e-4a13-8691-3aa77f0a3882}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	myString : STRING(1000) := '{"_id":null,"values":{"fbPump":{"volumePerRotation":0.0},"fbSqueegee":{"systemEnable":false},"fbSafety":null},"time_stamp":null}';
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>